OP_SRC_CONST = 1
OP_SRC_STEP = 2
OP_SRC_RAMP = 3
OP_SRC_SIN = 4
OP_SRC_TRIF = 5
OP_GAIN = 6
OP_SUM = 7
OP_CLARKE = 8
OP_INV_CLARKE = 9
OP_PARK = 10
OP_INV_PARK = 11
OP_INTEGRADOR = 12
OP_TF = 13
OP_PID = 14
OP_MAQ_INDUCCION = 15
OP_MAQ_SINCRONA = 16
OP_MAQ_PMAC = 17
OP_MAQ_CC = 18
OP_POT_BUCK = 19
OP_POT_BOOST = 20
OP_POT_BUCKBOOST = 21
OP_POT_RECT_3F = 22
OP_POT_INV_3F = 23
OP_EJE_MECANICO = 24
OP_PWM_1F    = 25
OP_PWM_SPWM  = 26
OP_PWM_SVPWM = 27
OP_HW_SERIAL = 28
OP_BATERIA   = 29
OP_SATURAR   = 30
OP_RELAY     = 31
OP_PULSO_RECT = 32
OP_PLL = 33
OP_POT_INV_1F = 34
OP_CARGA_RL_3F = 35
OP_TRANSFORMADOR = 36
OP_PANEL_SOLAR = 37
OP_MEDIDOR_POTENCIA = 38
OP_MAQ_DC_PM = 39
OP_INTERRUPTOR = 40
OP_DIODO = 41
OP_PUENTE_INV_3F = 42
OP_PUENTE_INV_1F = 43
OP_MUX = 44
OP_DEMUX = 45
OP_LUT1D = 46
OP_LUT2D = 47
OP_LUT3D = 48
OP_LOGICO = 49
OP_RELACIONAL = 50
OP_LIM_RAPIDEZ = 51
OP_RETENEDOR = 52
OP_MAQ_ESTADOS = 53
OP_MASA_TERMICA = 54
OP_RES_TERMICA = 55
OP_ENGRANAJE = 56
OP_EJE_FLEXIBLE = 57
OP_EMBRAGUE = 58
OP_SRC_CSV = 59
OP_FALLO_PROG = 60
OP_FALLO_EVENTO = 61
OP_MULTIPLICADOR = 62
OP_SAT_VECTORIAL = 63
OP_SRC_TABLE = 64
OP_BATERIA_ECM = 65
OP_CALCULO_IDC = 66
OP_VEHICULO = 67
OP_RESISTENCIA = 68
OP_INDUCTOR = 69
OP_CAPACITOR = 70
OP_QD = 71
OP_CARGA_PQ_3F = 72
OP_CARGA_PQ_1F = 73
OP_MUTUAL_INDUCTOR = 75
OP_VCVS = 76
OP_VCCS = 77
OP_MNA = 74
ES_ESTATICO = {
    OP_GAIN,
    OP_SUM,
    OP_CLARKE,
    OP_INV_CLARKE,
    OP_PARK,
    OP_INV_PARK,
    OP_PWM_1F,
    OP_PWM_SPWM,
    OP_PWM_SVPWM,
    OP_HW_SERIAL,
    OP_SATURAR,
    OP_TRANSFORMADOR,
    OP_PANEL_SOLAR,
    OP_MEDIDOR_POTENCIA,
    OP_INTERRUPTOR,
    OP_PUENTE_INV_3F,
    OP_PUENTE_INV_1F,
    OP_MUX,
    OP_DEMUX,
    OP_LUT1D,
    OP_LUT2D,
    OP_LUT3D,
    OP_LOGICO,
    OP_RELACIONAL,
    OP_RES_TERMICA,
    OP_ENGRANAJE,
    OP_EMBRAGUE,
    OP_FALLO_PROG,
    OP_FALLO_EVENTO,
    OP_MULTIPLICADOR,
    OP_SAT_VECTORIAL,
    OP_CALCULO_IDC,
    OP_RESISTENCIA,
    OP_QD,
    OP_CARGA_PQ_3F,
    OP_CARGA_PQ_1F,
    OP_VCVS,
    OP_VCCS,
}
ES_DINAMICO = {
    OP_INTEGRADOR,
    OP_TF,
    OP_PID,
    OP_MAQ_INDUCCION,
    OP_MAQ_SINCRONA,
    OP_MAQ_PMAC,
    OP_MAQ_CC,
    OP_MAQ_DC_PM,
    OP_POT_BUCK,
    OP_POT_BOOST,
    OP_POT_BUCKBOOST,
    OP_POT_RECT_3F,
    OP_POT_INV_3F,
    OP_POT_INV_1F,
    OP_CARGA_RL_3F,
    OP_BATERIA,
    OP_RELAY,
    OP_PLL,
    OP_EJE_MECANICO,
    OP_DIODO,
    OP_LIM_RAPIDEZ,
    OP_RETENEDOR,
    OP_MAQ_ESTADOS,
    OP_MASA_TERMICA,
    OP_EJE_FLEXIBLE,
    OP_BATERIA_ECM,
    OP_MUTUAL_INDUCTOR,
    OP_VEHICULO,
    OP_INDUCTOR,
    OP_CAPACITOR,
    OP_MNA,
}
